### ISSUE TITLE
Question about dependency injection

### ISSUE THREAD

**Issue by jim108dev** [lukaszkalnik/Moovis#2]
Hi @lukaszkalnik! I have read "Android functional Clean Architecture" and I was wondering how to do dependency injection since I am missing the Reader monad in the latest version of Arrow. Is this project also suppose to be Clean Architecture also? How can `UseCaseInjector` inside of `domain` depend on `data`?
Thanks.

**Comment by lukaszkalnik** [comment]
Can you elaborate a bit? I do manual dependency injection, that means by passing dependencies as arguments to constructors or factory functions.
I'm not sure what exactly you are asking about.

**Comment by jim108dev** [comment]
Thanks for the quick reply. Quoting from [The Clean Code Blog](https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html):

> The overriding rule that makes this architecture work is The Dependency Rule. This rule says that source code dependencies can only point inwards. Nothing in an inner circle can know anything at all about something in an outer circle. In particular, the name of something declared in an outer circle must not be mentioned by the code in the an inner circle. That includes, functions, classes. variables, or any other named software entity.

`domain` is in the inner circle, `data` outer. [UseCaseInjector.kt](https://github.com/lukaszkalnik/Moovis/blob/master/app/src/main/kotlin/com/lukaszkalnik/moovis/domain/UseCaseInjector.kt) uses `import com.lukaszkalnik.moovis.data.remote.TmdbApi`. Shouldn't the injector be declared further outside?

**Comment by lukaszkalnik** [comment]
If you look from the purist perspective then my architecture is indeed not Clean Architecture because of that.
The reason that was originally defined like that was because Clean Architecture was designed based on Java. Java has package access, so you could make the "inner circle" (which is the `domain` package) completely unaware of the outer circle (which is the `data` package). This way you could keep all the classes in the `data` package only package visible and compiler would enforce that your `domain` package remains completely isolated and the `data` implementations are interchangeable.

In Kotlin there is no package access (the closest is the `internal` modifier, but it defines module level visibility so you see all packages in your module anyway). So I took a shortcut here, which is ugly for Clean Architecture purists, but good enough for me.
It has the small disadvantage of not being able to replace the Retrofit API easily, which I don't intend to do. But the advantage is avoiding boilerplate of having a second interface for the Retrofit API inside the `domain` package which looks exactly the same.

You should do what works best for your project. If you intend to exchange something (like a Retrofit API for a database or Bluetooth module or some other Http library like Ktor) then hide it behind an additional interface. It will make your application more modular at the small cost of having some boilerplate.

Note that I can still use mocked Retrofit API in unit tests because it is defined as an interface anyway. If this weren't the case, I would have to hide my Http library behind an interface anyway just to make my domain code testable.

**Comment by jim108dev** [comment]
Why not move [UseCaseInjector.kt](https://github.com/lukaszkalnik/Moovis/blob/master/app/src/main/kotlin/com/lukaszkalnik/moovis/domain/UseCaseInjector.kt) into presentation, the entities into `domain` and api interfaces and data classes into `domain/repository` like in [fork](https://github.com/jim108dev/Moovis)? Wouldn't this qualify as Clean Architecture?

**Comment by lukaszkalnik** [comment]
This is just a hobby project which I have abandoned some time ago, as I have limited time for coding outside of my job... So I don't plan to spend more time on it.

**Comment by lukaszkalnik** [comment]
The point of Clean Architecture is to make the `domain` package completely self contained. So yes, if you create an interface which the `data` layer has to fulfill inside of the `domain` package, then it qualifies as Clean Architecture.

Where you put `UseCaseInjector` is not defined in CleanArchitecture, but it is also limited by the visibility of the classes it injects. `UseCaseInjector` must see the classes it injects.

But in this project dependency injection is manual and very basic, so I wouldn't recommend treating it as a reference for especially bigger projects.

**Comment by jim108dev** [comment]
Ok, well, thanks for spending the time. Out of interest, which would you recommend as a reference? I have seen
- [Android-CleanArchitecture-Kotlin](https://github.com/android10/Android-CleanArchitecture-Kotlin) and it uses `Retrofit` right in the core package.
- [ArrowAndroidSamples](https://github.com/JorgeCastilloPrz/ArrowAndroidSamples) is from 2019.

**Comment by lukaszkalnik** [comment]
I'm not familiar with any of them unfortunately...
I can recommend the Robert C. Martin's book and trying out what keeps your projects testable and maintainable in the long run ;)
There is no one universal rule for all projects, apart from "keep it modular and keep the modules which are likely to be exchanged/mocked exchangeable".

**Comment by jim108dev** [comment]
ok thx
